// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import { filterByGender, filterByBreed  } from "./filters"
import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationAutocompleteController from "./location_autocomplete_controller"
application.register("location-autocomplete", LocationAutocompleteController)

import SignupController from "./signup_controller"
application.register("signup", SignupController)



const genderDropdown = document.querySelector(".filter-param")
const breedDropdown = document.querySelector(".filter-param")

//event listener for GENDER
genderDropdown.addEventListener("change", (event) => {filterByGender(event.target.value)})
breedDropdown.addEventListener("change", (event) => {filterByBreed(event.target.value)})
