// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationAutocompleteController from "./location_autocomplete_controller"
application.register("location-autocomplete", LocationAutocompleteController)

import MapController from "./map_controller"
application.register("map", MapController)

import SignupController from "./signup_controller"
application.register("signup", SignupController)



const dropdown = document.querySelector(".filter-dropdown")

//event listener for GENDER
dropdown.addEventListener("change", (event) => {
  console.log(event.target.value)

  // Query selectors
  const cats = document.querySelectorAll(".cat-card")
  const catContainer = document.querySelector(".cards")

  // Converting DOM elements into an array
  const catArray = Array.from(cats)

  // filtering array by dataset
  const filteredCats = catArray.filter(cat => cat.dataset.gender === event.target.value)
  console.log(filteredCats)

  // wiping dom clean
  catContainer.innerHTML = "";

  // appending filtered cats into DOM
  filteredCats.forEach((item) => {
    catContainer.appendChild(item);
  })

})
